const products = [
    {
        _id: '1',
        name: 'product1',
        image: '/images/product1.jpg',
        description: 'description of product 1 for testing',
        brand: 'brand1',
        category: 'electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,

    },
    {
        _id: '2',
        name: 'product2',
        image: '/images/product2.jpg',
        description: 'description of product 2 for testing',
        brand: 'brand2',
        category: 'electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '3',
        name: 'product3',
        image: '/images/product3.jpg',
        description: 'description of product 3 for testing',
        brand: 'brand3',
        category: 'electronics',
        price: 70.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 5,
    },
    {
        _id: '4',
        name: 'product4',
        image: '/images/product4.jpg',
        description: 'description of product 4 for testing',
        brand: 'brand4',
        category: 'electronics',
        price: 10.99,
        countInStock: 5,
        rating: 4.5,
        numReviews: 4,
    },
]
export default products 